name: Edelleye
favicon: null
layout_spectrum: 0.0858950128313154
typography_spectrum: 0.8588929905090481
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7511648838408291
  lightness: 0.6450996205676347
  saturation: 0.28438754798844457
  rhythmicContrast: 0.5137575000990182
purpose: []
